---
- hosts: windows
  gather_facts: no
  tasks:
    - win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
        name: Version
      register: dotnetversion

    - debug: 
        msg: "{{dotnetversion}}"
       
