---
  - name: Install .NET Framework 4.8
    win_package:
      path: "https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0fd66638cde16859462a6243a4629a50/ndp48-x86-x64-allos-enu.exe"
      product_id: "{00377-10000-00000-AA360}"
      arguments: /install /passive /norestart
    register: dotnet48output

  - debug: 
      msg: "{{dotnet48output}}" 
